export const NOT_AUTHENTICATED_ERROR = 'NOT_AUTHENTICATED_ERROR';
export const NOT_AUTHORIZED_ERROR = 'NOT_AUTHORIZED_ERROR';

export const ACCESS_DESIGNER_DENIED_ERROR = 'ACCESS_DESIGNER_DENIED_ERROR';
export const ACCESS_WORKBENCH_DENIED_ERROR = 'ACCESS_WORKBENCH_DENIED_ERROR';
export const CREATE_REPORT_DENIED_ERROR = 'CREATE_REPORT_DENIED_ERROR';

export const PROJECT_NOT_FOUND_ERROR = 'PROJECT_NOT_FOUND_ERROR';
export const NO_PROJECT_AVAILABLE_ERROR = 'NO_PROJECT_AVAILABLE_ERROR';

export const DATA_TOO_LARGE_TO_DISPLAY = 'DATA_TOO_LARGE_TO_DISPLAY';

export const ENTITY_TOO_LARGE = 413;
export const INVALID_CONFIGURATION = 400;
export const INTERNAL_SERVER_ERROR = 500;
